apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
  namespace: dev
data:
  init-db.sql: |
    -- Create users table
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        active BOOLEAN DEFAULT TRUE,
        admin BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Create exercises table
    CREATE TABLE IF NOT EXISTS exercises (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        body TEXT NOT NULL,
        difficulty INTEGER NOT NULL,
        test_cases JSONB NOT NULL,
        solutions JSONB NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Create scores table
    CREATE TABLE IF NOT EXISTS scores (
        id SERIAL PRIMARY KEY,
        user_id INTEGER NOT NULL,
        exercise_id INTEGER NOT NULL,
        answer TEXT,
        results JSONB,
        user_results JSONB,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (exercise_id) REFERENCES exercises(id)
    );

    -- Insert default admin and user accounts
    -- Password for both: 123456 (bcrypt hash with rounds=13)
    INSERT INTO users (username, email, password, active, admin, created_at, updated_at)
    VALUES (
        'admin',
        'admin@example.com',
        '$2b$13$GpK7iJZCY3pB/kFwrl4FXexobRguAj0T8togYlZ1mZLXGv5KEDoNS',
        TRUE,
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (email) DO NOTHING;

    INSERT INTO users (username, email, password, active, admin, created_at, updated_at)
    VALUES (
        'phuochv',
        'phuochv@example.com',
        '$2b$13$GpK7iJZCY3pB/kFwrl4FXexobRguAj0T8togYlZ1mZLXGv5KEDoNS',
        TRUE,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
    ON CONFLICT (email) DO NOTHING;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-database
  namespace: dev
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: psql
        image: postgres:16-alpine
        command:
        - /bin/sh
        - -c
        - |
          # Drop and recreate database
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d postgres -c "DROP DATABASE IF EXISTS auth_db"
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d postgres -c "CREATE DATABASE auth_db"
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d auth_db -f /scripts/init-db.sql
        env:
        - name: DB_HOST
          value: "nt114-postgres-dev.cy7o684ygirj.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "AcgN2udlMatLllZooXyNKSojlEXR1E2t"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: init-db-script
      restartPolicy: Never
  backoffLimit: 3
