version: "3.3"

services:
  db:
    image: postgres:13
    container_name: sonarqube_db_1
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sonar"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - sonarqube_sonar-db:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_sonarqube_1
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_data:/opt/sonarqube/data

volumes:
  sonarqube_sonar-db:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_data:

