replicaCount: 1

image:
  repository: user-management-service
  pullPolicy: Never
  tag: "local"

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8081
  targetPort: 5001

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

env:
  - name: NODE_ENV
    value: "development"
  - name: PORT
    value: "8081"
  - name: FLASK_ENV
    value: "development"
  - name: DB_USER
    value: "postgres"
  - name: DB_PASSWORD
    value: "postgres"
  - name: DB_HOST
    value: "auth-db"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "auth_db"

podSecurityContext: {}

securityContext: {}

livenessProbe:
  httpGet:
    path: /api/auth/health
    port: 5001
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/auth/health
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
