apiVersion: v1
kind: Secret
metadata:
  name: repo-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/NT114DevSecOpsProject/NT114_DevSecOps_Project.git
  # For public repos, no credentials needed but we need to declare it
  insecure: "true"
