apiVersion: v2
name: api-gateway
description: A Helm chart for API Gateway microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - api-gateway
  - microservice
  - nodejs
maintainers:
  - name: NT114 DevSecOps Team
