replicaCount: 1

image:
  repository: api-gateway
  pullPolicy: Never
  tag: "local"

imagePullSecrets: []

service:
  type: NodePort
  port: 8080
  targetPort: 8000
  nodePort: 30081  # Access at localhost:30081

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

env:
  - name: NODE_ENV
    value: "development"
  - name: USER_SERVICE_URL
    value: "http://user-management-service:8081"
  - name: EXERCISES_SERVICE_URL
    value: "http://exercises-service:8082"
  - name: SCORES_SERVICE_URL
    value: "http://scores-service:8083"

podSecurityContext: {}

securityContext: {}

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
