apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 80.9.1
    helm:
      values: |
        # Global settings
        global:
          rbac:
            create: true

        # Prometheus Operator - Main controller
        prometheusOperator:
          admissionWebhooks:
            enabled: true  # ✅ Keep for validation
            patch:
              tolerations:
                - operator: Exists  # ✅ Schedule on any node
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
          tolerations:
            - key: workload
              operator: Equal
              value: monitoring
              effect: NoSchedule
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m

        # Prometheus - Time-series database
        prometheus:
          prometheusSpec:
            tolerations:
              - key: workload
                operator: Equal
                value: monitoring
                effect: NoSchedule
            replicas: 1
            retention: 7d
            retentionSize: 18GB
            walCompression: true
            resources:
              requests:
                memory: 512Mi
                cpu: 250m
              limits:
                memory: 1Gi
                cpu: 500m
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp3  # EBS CSI gp3 for better performance and lower cost
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            scrapeInterval: 60s
            evaluationInterval: 60s

        # Alertmanager - Alert routing
        alertmanager:
          alertmanagerSpec:
            tolerations:
              - key: workload
                operator: Equal
                value: monitoring
                effect: NoSchedule
            replicas: 1
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp3
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
            resources:
              requests:
                memory: 64Mi
                cpu: 50m
              limits:
                memory: 128Mi
                cpu: 100m

        # Grafana - Visualization
        grafana:
          tolerations:
            - key: workload
              operator: Equal
              value: monitoring
              effect: NoSchedule
          replicas: 1
          persistence:
            enabled: true
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            size: 10Gi
          admin:
            existingSecret: grafana-admin-credentials  # Created by workflow
            userKey: admin-user
            passwordKey: admin-password
          defaultDashboardsEnabled: true
          defaultDashboardsTimezone: Asia/Ho_Chi_Minh
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              searchNamespace: ALL
          service:
            type: ClusterIP  # Use ClusterIP for internal ALB
          ingress:
            enabled: true
            ingressClassName: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internal  # Internal ALB (production)
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
              alb.ingress.kubernetes.io/healthcheck-path: /api/health
              alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
              alb.ingress.kubernetes.io/group.name: internal-services  # Shared ALB with ArgoCD
            hosts:
              - grafana.internal.local
            paths:
              - /
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m

        # Kube State Metrics - Cluster state metrics
        kube-state-metrics:
          tolerations:
            - key: workload
              operator: Equal
              value: monitoring
              effect: NoSchedule
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m

        # Node Exporter - Node metrics (runs on ALL nodes)
        prometheus-node-exporter:
          tolerations:
            - operator: Exists  # Must run on all nodes
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 100m
          hostNetwork: true
          hostPID: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true       # ✅ Auto cleanup deleted resources
      selfHeal: true    # ✅ Auto fix drift
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Better for large manifests
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
