apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-management-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nt114-devsecops

  source:
    repoURL: https://github.com/conghieu2004/NT114_DevSecOps_Project.git
    targetRevision: main
    path: helm/user-management-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: image.repository
          value: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/user-management-service

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
